name: Maven Reusable Workflow
run-name: GitHub Action Maven Reusable Workflow
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      git_token:
        required: true
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tools repo
      run: |
        git clone https://anujdevopslearn:${{ secrets.git_token }}@github.com/anujdevopslearn/PythonTest test
    - name: Invoke Python script
      run: python -m unittest discover
      working-directory: test/example-py-unittest/
