name: Tomcat Reusable Workflow
run-name: GitHub Action Tomcat Reusable Workflow
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Tomcat-Workflow:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/download-artifact@v3
       with:
         name: buildArtifact
     - name: Production Deployment
       run: |
          ls -lart 
          echo ${{ secrets.DC_HOST }}
     - name: scp ssh pipelines
       uses: cross-the-world/ssh-scp-ssh-pipelines@latest
       env:
         LASTSSH: "Doing something after copying"
       with:
         host: ${{ secrets.DC_HOST }}
         user: ${{ secrets.DC_USER }}
         pass: ${{ secrets.DC_KEY }}
         scp: |
          ./*.war => /tmp/
         last_ssh: |
            sudo cp /tmp/*.war /var/lib/tomcat9/webapps/Anuj.war
            ls -la
